version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'data'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      start_period: 60s
      interval: 5s
      retries: 3

  api:
    build: src/api
    restart: always
    ports:
      - ${API_PORT}:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/data

  client:
    build: .
    restart: always
    tty: true
    stdin_open: true
    ports:
      - ${CLIENT_PORT}:3000
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
